### ISSUE TITLE
As a user, I can assign the classrooms for each course session, so that I can better plan out the location requirements.

### ISSUE THREAD

**Issue by ShengXue97** [AY1920S2-CS2103-W14-1/main#32]

**Comment by h12567** [comment]
@ShengXue97  @ivanteejj Can you please elaborate on these requirements:
- What should be the format of location? GPS ? Or like building/room number?

- What kind of location plannings examples are there?

**Comment by ivanteejj** [comment]
> @ShengXue97 @ivanteejj Can you please elaborate on these requirements:
> 
> * What should be the format of location? GPS ? Or like building/room number?
> * What kind of location plannings examples are there?

I think we should assume 1 class room and 1 location for 1 with the possibility to extend in the future. I suppose, we can do building/room number. Honestly, the priority should be low for this. Have adjusted accordingly.
